### ISSUE TITLE
Installing in termux (and possibly other prefix environments)

### ISSUE THREAD

**Issue by T313C0mun1s7** [awsdocs/aws-cli-user-guide#11]
Termux is a popular way to get a Linux shell running very easily on Android without the need for root. As such it is a prefixed environment (https://wiki.termux.com/wiki/FAQ#Is_Termux_a_complete_Linux_Environment.3F) so installing it using the *--user* option prevents it from working. Simply omitting the *--user* option from the install command string allows it to work as expected.

The documentation should be updated to reflect this as it is not obvious to the uninitiated (like myself.) I was unable to find any guidance in all of my searching to lead me to this and only figured it out via dumb luck and not giving up. It order to make installing easier for others using termux, and possibly other prefixed environments, please note this in both the main install page and the Linux install page of the documentation.

**Comment by bisdavid** [comment]
I'll review this and consider.  However, can't reasonably document every variant of Linux - and Termux isn't even an operating system, it's only a Linux-like shell running on top of Android.

**Comment by PePoDev** [comment]
@bisdavid 
How to install aws cli on Termux ?
I try with aws document (v2, arm) and it's not working. It's show

```
./aws/install: 78: /home/aws/dist/aws: not found
You can now run: /usr/local/bin/aws --version
```

But when I run `/usr/local/bin/aws --version` I got `no command are found`

**Comment by elysahall** [comment]
We support the AWS CLI version 2 on 64-bit versions of recent distributions of CentOS, Fedora, Ubuntu, Amazon Linux 1, and Amazon Linux 2. Termux isn't an operating system, it's only a Linux-like shell running on top of Android. If you need specific help trying to get CLI v2 on Termux, I'd suggest going to the AWS CLI developer github where the developers, support, and community can help you. 
https://github.com/aws/aws-cli

**Comment by missingcharacter** [comment]
@PePoDev and @T313C0mun1s7 this may help you https://github.com/missingcharacter/termux-dot-files#install-aws-cli

**Comment by AEiosApp** [comment]
Thanks to @ChaosMarc, here's how it worked for me:

````
# Install Termux via F-Droid instead of Google Play Store
apt update
apt -y upgrade
# I chose to answer all questions regarding conflicts with "y"
apt -y install git python rust build-essential
# Install awscli
pip3 install awscli
# Configure awscli
aws configure
````

**Comment by ChaosMarc** [comment]
@AEiosApp sadly this installs v1 instead of v2 which doesn't have sso support for once
