### ISSUE TITLE
Mention of snap package

### ISSUE THREAD

**Issue by alejandroandreu** [awsdocs/aws-cli-user-guide#17]
There is a verified `aws-cli` package on Snapcraft[1]. I think it would be wise to advertise this package for Linux desktop users.

[1]: https://snapcraft.io/aws-cli

**Comment by bisdavid** [comment]
Thanks for your feedback. We have chosen not to directly reference any package sources that are not owned or maintained by AWS. We can't be held accountable for content over which we have no control. I'm sorry for the inconvenience, but it's basically a legal issue.
