### ISSUE TITLE
Link to Windows MSI is out of date

### ISSUE THREAD

**Issue by BradKnowles** [awsdocs/aws-cli-user-guide#26]
The link to the Windows MSI on page `install-cliv2-windows.md` is out of date.  It points to 1.16.269 which was released in October 2019.

I used https://s3.amazonaws.com/aws-cli/AWSCLI64PY3-1.18.1.msi to get the latest version.

**Comment by elysahall** [comment]
Hi Brad,
Thanks for bringing this to our attention. It looks like we new use the generic AWSCLIV2 filename for current versions to bypass having very specific version numbers for current installers.
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html
