### ISSUE TITLE
CLI v2 is not shipping aws_zsh_completer.sh like v1 did.

### ISSUE THREAD

**Issue by KaibaLopez** [awsdocs/aws-cli-user-guide#27]
Hi, we've got an issue : aws/aws-cli#4950
The thing is the .sh file is not part of the CLI v2 installation, so users would either have to add:
```
autoload bashcompinit
bashcompinit
complete -C '/usr/local/bin/aws_completer' aws
```
to their .zshrc file, or install oh-my-zsh to enable auto complete.
Could there be a warning added to the [install instructions ](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html)?

**Comment by bisdavid** [comment]
We are aware of that, and the CLI engineering team intends to ship an update with that as soon as they can.

**Comment by zaiddabaeen** [comment]
The issue persists until today with latest CLI for Mac.

The temporary workaround is still the one posted above https://github.com/awsdocs/aws-cli-user-guide/issues/27#issue-566559742
