### ISSUE TITLE
CLI V2 install prerequisites

### ISSUE THREAD

**Issue by KaibaLopez** [awsdocs/aws-cli-user-guide#28]
Hi,
For the V2 of the CLI, the output changed to be paginated by default and it uses the commands [less](https://ss64.com/bash/less.html) for mac and linux, and the command [more](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/more) for windows. As far as I know there is no way for windows to not have the command unless explicitly uninstalled, but for some linux distributions it could happen.
This [issue](https://github.com/aws/aws-cli/issues/5038#issuecomment-595509982) brought this to our attention, and I wanted to see if we can add **less** to the list of requirements for linux at least.

**Comment by elysahall** [comment]
Thank you for bringing this to our attention. We updated the prerequisites for Linux:
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
