### ISSUE TITLE
CLI V2 `brew` installation option for Mac OS

### ISSUE THREAD

**Issue by hervenivon** [awsdocs/aws-cli-user-guide#35]
Why not mentioning the `brew` method to install the AWS CLI in the documentation `https://github.com/awsdocs/aws-cli-user-guide/blob/master/doc_source/install-cliv2-mac.md`?

`brew` is a common Mac package manager which is very convenient to install and upgrade the AWS CLI:

- Installation: `brew install awscli`
- Upgrade: `brew upgrade awscli`

**Comment by elysahall** [comment]
Hi Hervé,
Currently the CLI team does not maintain third-party repositories for the CLI v2, and therefore we don't recommend them. If you'd like repositories such as homebrew to be supported, I'd suggest making a feature request on the [AWS CLI GitHub](https://github.com/aws/aws-cli/).

For some more discussion and the CLI dev team responses on this topic regarding CLI v2, see [this GitHub issue regarding pip](https://github.com/aws/aws-cli/issues/4947).

**Comment by hauntingEcho** [comment]
@hervenivon you may be interested in the discussion of the homebrew formula here: https://github.com/aws/aws-cli/issues/727
