### ISSUE TITLE
Potential security issue with this command

### ISSUE THREAD

**Issue by manuelh2410** [awsdocs/aws-cli-user-guide#60]
Good Day , 

In "https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec2-sg.html#configuring-a-security-group"
You mention the following  security group configuration :

"aws ec2 authorize-security-group-ingress --group-id sg-903004f8 --protocol tcp --port 3389 --cidr 203.0.113.0/24"

This can form a potential security risk. 

I have simplified the security group configuration to the following two lines to ensure that only 1 IP address has RDP access to the instance the security group has been linked to .   

#Retrieve public IP and store in variable
@FOR /f "delims=" %i in ('curl https://checkip.amazonaws.com') DO set IP=%i/32

#Grant Access to single IP stored in variable 
aws ec2 authorize-security-group-ingress --group-id sg-903004f8 --protocol tcp --port 3389 --cidr %IP%

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
