### ISSUE TITLE
ModuleNotFoundError AWS CLI V2

### ISSUE THREAD

**Issue by gungunfebrianza** [awsdocs/aws-cli-user-guide#68]
Hello guys
seems on my windows its not working.

First i install AWS CLI V2 here :
https://awscli.amazonaws.com/AWSCLIV2.msi

then open my cmd.exe execute this command : 
`aws --version`

and here what i got : 

```
C:\Windows\System32>aws --version
Traceback (most recent call last):
  File "C:\Users\Marketkoin\AppData\Local\Programs\Python\Python38-32\Scripts\aws.cmd", line 50, in <module>
    import awscli.clidriver
ModuleNotFoundError: No module named 'awscli'
```

even after i am adding the path manually from : 
C:\Program Files\Amazon\AWSCLIV2

to my environment path variable, the problem still persist.

thx

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
