### ISSUE TITLE
Broken link on "Using the AWS CLI to work with AWS Services"

### ISSUE THREAD

**Issue by connorjburton** [awsdocs/aws-cli-user-guide#75]
The link [AWS CLI version 2 reference guide](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/) on [this page](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-services.html) goes to a 404 page.

**Comment by elysahall** [comment]
Resolved. Thanks for pointing this out.
