### ISSUE TITLE
Set vs Setx

### ISSUE THREAD

**Issue by Pl4nky** [awsdocs/aws-cli-user-guide#76]
Instructions for setting the proxy on a windows host mentions using the 'setx' command. Variables set with this command cannot be used by the AWS CLI. 

The example provided should be using SET as opposed to SETX:
```
C:\> set HTTP_PROXY=http://10.15.20.25:1234
C:\> set HTTP_PROXY=http://proxy.example.com:1234
C:\> set HTTPS_PROXY=http://10.15.20.25:5678
C:\> set HTTPS_PROXY=http://proxy.example.com:5678
```

Once set is used, the CLI is able to read the variables and use the proxy as defined.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
