### ISSUE TITLE
AWS-Shell should not be promoted on the marketing website for CLI

### ISSUE THREAD

**Issue by omenking** [awsdocs/aws-cli-user-guide#87]
This is the marketing website, but it is AWS Docs, and its quite misleading.

So here at https://aws.amazon.com/cli/ it talks about the AWS Shell

![image](https://user-images.githubusercontent.com/7776/201169024-c47c79f6-f9c1-4260-9b31-6ac27131bf31.png)

The problem is that this project has not had any code updates since 2020 and is throwing errors.

https://github.com/awslabs/aws-shell/issues/266

It looks like AWS-Shell was rolled directly into the AWS CLI since you can run the following command and get a similar experience.

```
aws --cli-auto-prompt
```

The issue is that to me it looked like an active project, and so I spent a good chunk of my day preparing free video content to learn this tool, but it doesn't look like it should be used.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
