### ISSUE TITLE
Pip path incorrect

### ISSUE THREAD

**Issue by marcoValkyriweb** [awsdocs/aws-cli-user-guide#9]
Hi, 

https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#awscli-install-windows-path

The pip path is wrong. 
%APPDATA%\Roaming\Python\Python37\Scripts is correct: https://github.com/aws/aws-cli/issues/3181#issuecomment-375114868

If you omit the --user, it will install in the local/programs/python#version#/scripts folder. One should either remove the --user from the suggestion or change the path to the correct one.

**Comment by renbud** [comment]
Agree with marcoValkyriweb.  On Windows 10 was
>  pip install --user --upgrade awscli

installs to 

 %APPDATA%\Roaming\Python\Python37\Scripts

**Comment by bisdavid** [comment]
This appears to be a difference between Windows 10 and earlier versions of Windows.  I've updated the docs accordingly.

Thanks for reporting this!
